//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENLSYS.MES.Win.wsINP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsINP.IwsINP")]
    public interface IwsINP {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetShippingSumRecords", ReplyAction="http://tempuri.org/IwsINP/GetShippingSumRecordsResponse")]
        System.Data.DataSet GetShippingSumRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetShippingSumDtlRecords", ReplyAction="http://tempuri.org/IwsINP/GetShippingSumDtlRecordsResponse")]
        System.Data.DataSet GetShippingSumDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetUnShippingSumRecords", ReplyAction="http://tempuri.org/IwsINP/GetUnShippingSumRecordsResponse")]
        System.Data.DataSet GetUnShippingSumRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetUnShippingSumDtlRecords", ReplyAction="http://tempuri.org/IwsINP/GetUnShippingSumDtlRecordsResponse")]
        System.Data.DataSet GetUnShippingSumDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/HasShipByPlanNo", ReplyAction="http://tempuri.org/IwsINP/HasShipByPlanNoResponse")]
        bool HasShipByPlanNo(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingplanno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetPackingCartonRecords", ReplyAction="http://tempuri.org/IwsINP/GetPackingCartonRecordsResponse")]
        System.Data.DataSet GetPackingCartonRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetPackingCartonSummaryRecords", ReplyAction="http://tempuri.org/IwsINP/GetPackingCartonSummaryRecordsResponse")]
        System.Data.DataSet GetPackingCartonSummaryRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoXUnpacking", ReplyAction="http://tempuri.org/IwsINP/DoXUnpackingResponse")]
        void DoXUnpacking(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string[][] lstunpacking);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetPackingRecDtlRecords", ReplyAction="http://tempuri.org/IwsINP/GetPackingRecDtlRecordsResponse")]
        System.Data.DataSet GetPackingRecDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetPackingDtlSumRecords", ReplyAction="http://tempuri.org/IwsINP/GetPackingDtlSumRecordsResponse")]
        System.Data.DataSet GetPackingDtlSumRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetPackingDtlRecords", ReplyAction="http://tempuri.org/IwsINP/GetPackingDtlRecordsResponse")]
        System.Data.DataSet GetPackingDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetHaveNotMovingDtlSumRecords", ReplyAction="http://tempuri.org/IwsINP/GetHaveNotMovingDtlSumRecordsResponse")]
        System.Data.DataSet GetHaveNotMovingDtlSumRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetHaveNotMovingDtlRecords", ReplyAction="http://tempuri.org/IwsINP/GetHaveNotMovingDtlRecordsResponse")]
        System.Data.DataSet GetHaveNotMovingDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetHaveNotPackingDtlSumRecords", ReplyAction="http://tempuri.org/IwsINP/GetHaveNotPackingDtlSumRecordsResponse")]
        System.Data.DataSet GetHaveNotPackingDtlSumRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetHaveNotPackingDtlRecords", ReplyAction="http://tempuri.org/IwsINP/GetHaveNotPackingDtlRecordsResponse")]
        System.Data.DataSet GetHaveNotPackingDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetLineWarehouseSumRecords", ReplyAction="http://tempuri.org/IwsINP/GetLineWarehouseSumRecordsResponse")]
        System.Data.DataSet GetLineWarehouseSumRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetLineWarehouseSumDtlRecords", ReplyAction="http://tempuri.org/IwsINP/GetLineWarehouseSumDtlRecordsResponse")]
        System.Data.DataSet GetLineWarehouseSumDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetPackingRecRetrieveRecords", ReplyAction="http://tempuri.org/IwsINP/GetPackingRecRetrieveRecordsResponse")]
        System.Data.DataSet GetPackingRecRetrieveRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetOtherPricingList", ReplyAction="http://tempuri.org/IwsINP/GetOtherPricingListResponse")]
        GENLSYS.MES.DataContracts.tinpotherpricing[] GetOtherPricingList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetOtherPricingRecords", ReplyAction="http://tempuri.org/IwsINP/GetOtherPricingRecordsResponse")]
        System.Data.DataSet GetOtherPricingRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSingleOtherPricing", ReplyAction="http://tempuri.org/IwsINP/GetSingleOtherPricingResponse")]
        GENLSYS.MES.DataContracts.tinpotherpricing GetSingleOtherPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoInsertOtherPricing", ReplyAction="http://tempuri.org/IwsINP/DoInsertOtherPricingResponse")]
        void DoInsertOtherPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpotherpricing otherpricing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoUpdateOtherPricing", ReplyAction="http://tempuri.org/IwsINP/DoUpdateOtherPricingResponse")]
        void DoUpdateOtherPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpotherpricing otherpricing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoDeleteOtherPricing", ReplyAction="http://tempuri.org/IwsINP/DoDeleteOtherPricingResponse")]
        void DoDeleteOtherPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetValidOtherPricing", ReplyAction="http://tempuri.org/IwsINP/GetValidOtherPricingResponse")]
        System.Data.DataSet GetValidOtherPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string customerid, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoInsertRequestPay", ReplyAction="http://tempuri.org/IwsINP/DoInsertRequestPayResponse")]
        void DoInsertRequestPay(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinprequestpay requestPay, GENLSYS.MES.DataContracts.tinprequestpaydtl[] lstDtl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSingleRequestPay", ReplyAction="http://tempuri.org/IwsINP/GetSingleRequestPayResponse")]
        GENLSYS.MES.DataContracts.tinprequestpay GetSingleRequestPay(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetRequestPayDtlRecords", ReplyAction="http://tempuri.org/IwsINP/GetRequestPayDtlRecordsResponse")]
        System.Data.DataSet GetRequestPayDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSingleRepairHis", ReplyAction="http://tempuri.org/IwsINP/GetSingleRepairHisResponse")]
        GENLSYS.MES.DataContracts.tinprepairhis GetSingleRepairHis(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoRepaireAdjust", ReplyAction="http://tempuri.org/IwsINP/DoRepaireAdjustResponse")]
        void DoRepaireAdjust(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string repsysid, string reasoncode, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetLeftRepairSuccessQty", ReplyAction="http://tempuri.org/IwsINP/GetLeftRepairSuccessQtyResponse")]
        int GetLeftRepairSuccessQty(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string custorderno, string styleno, string color, string size, string step);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetRepairInfoForInspectRpt", ReplyAction="http://tempuri.org/IwsINP/GetRepairInfoForInspectRptResponse")]
        System.Data.DataSet GetRepairInfoForInspectRpt(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetRepairFailForInspectRpt", ReplyAction="http://tempuri.org/IwsINP/GetRepairFailForInspectRptResponse")]
        System.Data.DataSet GetRepairFailForInspectRpt(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetShippedForInspectRpt", ReplyAction="http://tempuri.org/IwsINP/GetShippedForInspectRptResponse")]
        System.Data.DataSet GetShippedForInspectRpt(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetHeaderInfoForInspectRpt", ReplyAction="http://tempuri.org/IwsINP/GetHeaderInfoForInspectRptResponse")]
        System.Data.DataSet GetHeaderInfoForInspectRpt(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoReturn", ReplyAction="http://tempuri.org/IwsINP/DoReturnResponse")]
        void DoReturn(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpreturn inpreturn, GENLSYS.MES.DataContracts.tinpreturndtl[] lstreturndtl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetReturnDtlRecords", ReplyAction="http://tempuri.org/IwsINP/GetReturnDtlRecordsResponse")]
        System.Data.DataSet GetReturnDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSingleReturn", ReplyAction="http://tempuri.org/IwsINP/GetSingleReturnResponse")]
        GENLSYS.MES.DataContracts.tinpreturn GetSingleReturn(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoSupplement", ReplyAction="http://tempuri.org/IwsINP/DoSupplementResponse")]
        void DoSupplement(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpsupplement supplement, GENLSYS.MES.DataContracts.tinpsupplementdtl[] lstsupplementdtl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSupplementDtlRecords", ReplyAction="http://tempuri.org/IwsINP/GetSupplementDtlRecordsResponse")]
        System.Data.DataSet GetSupplementDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoSupplementAdjust", ReplyAction="http://tempuri.org/IwsINP/DoSupplementAdjustResponse")]
        void DoSupplementAdjust(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string supldtlsysid, int qty, string isreinspect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSingleShipping", ReplyAction="http://tempuri.org/IwsINP/GetSingleShippingResponse")]
        GENLSYS.MES.DataContracts.tinpshipping GetSingleShipping(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetShippingRecords", ReplyAction="http://tempuri.org/IwsINP/GetShippingRecordsResponse")]
        System.Data.DataSet GetShippingRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSingleShippingDtl", ReplyAction="http://tempuri.org/IwsINP/GetSingleShippingDtlResponse")]
        GENLSYS.MES.DataContracts.tinpshippingdtl GetSingleShippingDtl(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetShippingDtlRecords", ReplyAction="http://tempuri.org/IwsINP/GetShippingDtlRecordsResponse")]
        System.Data.DataSet GetShippingDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetShippingPlanNoRecords", ReplyAction="http://tempuri.org/IwsINP/GetShippingPlanNoRecordsResponse")]
        System.Data.DataSet GetShippingPlanNoRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingsysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoDeleteShipping", ReplyAction="http://tempuri.org/IwsINP/DoDeleteShippingResponse")]
        void DoDeleteShipping(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingsysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetShippingDtlForReport", ReplyAction="http://tempuri.org/IwsINP/GetShippingDtlForReportResponse")]
        System.Data.DataSet GetShippingDtlForReport(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingsysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetShippingOrigDtlForReport", ReplyAction="http://tempuri.org/IwsINP/GetShippingOrigDtlForReportResponse")]
        System.Data.DataSet GetShippingOrigDtlForReport(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingsysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetShippingDtlForWarehouseOut", ReplyAction="http://tempuri.org/IwsINP/GetShippingDtlForWarehouseOutResponse")]
        System.Data.DataSet GetShippingDtlForWarehouseOut(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingsysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetBillForBillingReport", ReplyAction="http://tempuri.org/IwsINP/GetBillForBillingReportResponse")]
        System.Data.DataSet GetBillForBillingReport(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingsysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetShippingDtlCtnRecords", ReplyAction="http://tempuri.org/IwsINP/GetShippingDtlCtnRecordsResponse")]
        System.Data.DataSet GetShippingDtlCtnRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetShippingPlanRecords", ReplyAction="http://tempuri.org/IwsINP/GetShippingPlanRecordsResponse")]
        System.Data.DataSet GetShippingPlanRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoShipPlan", ReplyAction="http://tempuri.org/IwsINP/DoShipPlanResponse")]
        void DoShipPlan(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpshippingdtl[] lstshippingdtl, GENLSYS.MES.DataContracts.tinpshippingplan shippingplan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoShipping", ReplyAction="http://tempuri.org/IwsINP/DoShippingResponse")]
        void DoShipping(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpshipping shipping, GENLSYS.MES.DataContracts.tinpshippingdtlctn[] lstshippingdtlctn, GENLSYS.MES.DataContracts.tinpshippingplan shippingplan, bool isDoShipping);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSingleShippingPlan", ReplyAction="http://tempuri.org/IwsINP/GetSingleShippingPlanResponse")]
        GENLSYS.MES.DataContracts.tinpshippingplan GetSingleShippingPlan(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetReceivingDetail_Print", ReplyAction="http://tempuri.org/IwsINP/GetReceivingDetail_PrintResponse")]
        System.Data.DataSet GetReceivingDetail_Print(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string recno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetReceivingSumCtnDtlRecords", ReplyAction="http://tempuri.org/IwsINP/GetReceivingSumCtnDtlRecordsResponse")]
        System.Data.DataSet GetReceivingSumCtnDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetReceivingCtnDtlRecords", ReplyAction="http://tempuri.org/IwsINP/GetReceivingCtnDtlRecordsResponse")]
        System.Data.DataSet GetReceivingCtnDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/UpdateCartonQty", ReplyAction="http://tempuri.org/IwsINP/UpdateCartonQtyResponse")]
        void UpdateCartonQty(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string recsysid, string cartonno, string oldstyleno, string oldcolor, string oldsize, int quantity, string color, string size, string styleno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DeleteSingleCarton", ReplyAction="http://tempuri.org/IwsINP/DeleteSingleCartonResponse")]
        void DeleteSingleCarton(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string recsysid, string cartonno, string oldstyleno, string oldcolor, string oldsize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/CheckReceivingUsed", ReplyAction="http://tempuri.org/IwsINP/CheckReceivingUsedResponse")]
        bool CheckReceivingUsed(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string recsysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetIQCList", ReplyAction="http://tempuri.org/IwsINP/GetIQCListResponse")]
        GENLSYS.MES.DataContracts.tinpiqc[] GetIQCList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetIQCRecords", ReplyAction="http://tempuri.org/IwsINP/GetIQCRecordsResponse")]
        System.Data.DataSet GetIQCRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSingleIQC", ReplyAction="http://tempuri.org/IwsINP/GetSingleIQCResponse")]
        GENLSYS.MES.DataContracts.tinpiqc GetSingleIQC(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoInsertIQC", ReplyAction="http://tempuri.org/IwsINP/DoInsertIQCResponse")]
        void DoInsertIQC(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpiqc iqc, GENLSYS.MES.DataContracts.tinpiqcfail[] lstFail, GENLSYS.MES.DataContracts.tinpiqcreturn[] lstReturn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoUpdateIQC", ReplyAction="http://tempuri.org/IwsINP/DoUpdateIQCResponse")]
        void DoUpdateIQC(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpiqc iqc, GENLSYS.MES.DataContracts.tinpiqcfail[] lstFail, GENLSYS.MES.DataContracts.tinpiqcreturn[] lstReturn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoDeleteIQC", ReplyAction="http://tempuri.org/IwsINP/DoDeleteIQCResponse")]
        void DoDeleteIQC(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetIQCFail", ReplyAction="http://tempuri.org/IwsINP/GetIQCFailResponse")]
        System.Data.DataSet GetIQCFail(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string iqcsysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetIQCReturn", ReplyAction="http://tempuri.org/IwsINP/GetIQCReturnResponse")]
        System.Data.DataSet GetIQCReturn(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string iqcsysid, string styleno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetValidIQC", ReplyAction="http://tempuri.org/IwsINP/GetValidIQCResponse")]
        System.Data.DataSet GetValidIQC(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string customerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetScheduleList", ReplyAction="http://tempuri.org/IwsINP/GetScheduleListResponse")]
        GENLSYS.MES.DataContracts.tinpschedule[] GetScheduleList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetScheduleRecords", ReplyAction="http://tempuri.org/IwsINP/GetScheduleRecordsResponse")]
        System.Data.DataSet GetScheduleRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoDeleteSchedule", ReplyAction="http://tempuri.org/IwsINP/DoDeleteScheduleResponse")]
        void DoDeleteSchedule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoInsertSchedule", ReplyAction="http://tempuri.org/IwsINP/DoInsertScheduleResponse")]
        void DoInsertSchedule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string yearmonth, GENLSYS.MES.DataContracts.tinpschedule[] lstSchedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoUpdateSchedule", ReplyAction="http://tempuri.org/IwsINP/DoUpdateScheduleResponse")]
        void DoUpdateSchedule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string yearmonth, GENLSYS.MES.DataContracts.tinpschedule[] lstSchedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetDailySchedule", ReplyAction="http://tempuri.org/IwsINP/GetDailyScheduleResponse")]
        System.Data.DataSet GetDailySchedule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetCustOrderHistoryRecords", ReplyAction="http://tempuri.org/IwsINP/GetCustOrderHistoryRecordsResponse")]
        System.Data.DataSet GetCustOrderHistoryRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetRepairFailRecords", ReplyAction="http://tempuri.org/IwsINP/GetRepairFailRecordsResponse")]
        System.Data.DataSet GetRepairFailRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetRepairStockRecords", ReplyAction="http://tempuri.org/IwsINP/GetRepairStockRecordsResponse")]
        System.Data.DataSet GetRepairStockRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSingleRepairStock", ReplyAction="http://tempuri.org/IwsINP/GetSingleRepairStockResponse")]
        GENLSYS.MES.DataContracts.tinprepairstock GetSingleRepairStock(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoInsertRepair", ReplyAction="http://tempuri.org/IwsINP/DoInsertRepairResponse")]
        void DoInsertRepair(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinprepairhis repairhis, GENLSYS.MES.DataContracts.tinprepairfail[] lstreasoncode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoRepairBack", ReplyAction="http://tempuri.org/IwsINP/DoRepairBackResponse")]
        void DoRepairBack(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinprepairstock repairstock, GENLSYS.MES.DataContracts.tinprepairfail[] lstreasoncode, string jointtype, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetRepairHisRecords", ReplyAction="http://tempuri.org/IwsINP/GetRepairHisRecordsResponse")]
        System.Data.DataSet GetRepairHisRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoWork", ReplyAction="http://tempuri.org/IwsINP/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetCustOrderRecords", ReplyAction="http://tempuri.org/IwsINP/GetCustOrderRecordsResponse")]
        System.Data.DataSet GetCustOrderRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetWipList", ReplyAction="http://tempuri.org/IwsINP/GetWipListResponse")]
        GENLSYS.MES.DataContracts.tinpwip[] GetWipList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetWipRecords", ReplyAction="http://tempuri.org/IwsINP/GetWipRecordsResponse")]
        System.Data.DataSet GetWipRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSingleWip", ReplyAction="http://tempuri.org/IwsINP/GetSingleWipResponse")]
        GENLSYS.MES.DataContracts.tinpwip GetSingleWip(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetLeftWipRecords", ReplyAction="http://tempuri.org/IwsINP/GetLeftWipRecordsResponse")]
        System.Data.DataSet GetLeftWipRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetWorkOrderList", ReplyAction="http://tempuri.org/IwsINP/GetWorkOrderListResponse")]
        GENLSYS.MES.DataContracts.tinpworkorder[] GetWorkOrderList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetWorkOrderRecords", ReplyAction="http://tempuri.org/IwsINP/GetWorkOrderRecordsResponse")]
        System.Data.DataSet GetWorkOrderRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSingleWorkOrder", ReplyAction="http://tempuri.org/IwsINP/GetSingleWorkOrderResponse")]
        GENLSYS.MES.DataContracts.tinpworkorder GetSingleWorkOrder(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoInsertWorkOrder", ReplyAction="http://tempuri.org/IwsINP/DoInsertWorkOrderResponse")]
        void DoInsertWorkOrder(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpworkorder workorder, GENLSYS.MES.DataContracts.tinpworkorderdtl[] lstDtl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoUpdateWorkOrder", ReplyAction="http://tempuri.org/IwsINP/DoUpdateWorkOrderResponse")]
        void DoUpdateWorkOrder(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpworkorder workorder, GENLSYS.MES.DataContracts.tinpworkorderdtl[] lstDtl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoDeleteWorkOrder", ReplyAction="http://tempuri.org/IwsINP/DoDeleteWorkOrderResponse")]
        void DoDeleteWorkOrder(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetWorkOrderDetailRecords", ReplyAction="http://tempuri.org/IwsINP/GetWorkOrderDetailRecordsResponse")]
        System.Data.DataSet GetWorkOrderDetailRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetCustOrderForReceiving", ReplyAction="http://tempuri.org/IwsINP/GetCustOrderForReceivingResponse")]
        System.Data.DataSet GetCustOrderForReceiving(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSinglePricing", ReplyAction="http://tempuri.org/IwsINP/GetSinglePricingResponse")]
        GENLSYS.MES.DataContracts.tinppricing GetSinglePricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetPricingRecords", ReplyAction="http://tempuri.org/IwsINP/GetPricingRecordsResponse")]
        System.Data.DataSet GetPricingRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoInsertPricing", ReplyAction="http://tempuri.org/IwsINP/DoInsertPricingResponse")]
        void DoInsertPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinppricing prc, GENLSYS.MES.DataContracts.tinppricingdtl[] lstPrcDtl, GENLSYS.MES.DataContracts.tinppricingdtldef[] lstDef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoUpdatePricing", ReplyAction="http://tempuri.org/IwsINP/DoUpdatePricingResponse")]
        void DoUpdatePricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinppricing prc, GENLSYS.MES.DataContracts.tinppricingdtl[] lstPrcDtl, GENLSYS.MES.DataContracts.tinppricingdtldef[] lstDef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetValidPricing", ReplyAction="http://tempuri.org/IwsINP/GetValidPricingResponse")]
        System.Data.DataSet GetValidPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string customerid, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetReceivingList", ReplyAction="http://tempuri.org/IwsINP/GetReceivingListResponse")]
        GENLSYS.MES.DataContracts.tinpreceiving[] GetReceivingList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetReceivingRecords", ReplyAction="http://tempuri.org/IwsINP/GetReceivingRecordsResponse")]
        System.Data.DataSet GetReceivingRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetSingleReceiving", ReplyAction="http://tempuri.org/IwsINP/GetSingleReceivingResponse")]
        GENLSYS.MES.DataContracts.tinpreceiving GetSingleReceiving(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoInsertReceiving", ReplyAction="http://tempuri.org/IwsINP/DoInsertReceivingResponse")]
        void DoInsertReceiving(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpreceiving rec, GENLSYS.MES.DataContracts.tinpreceivingdtl[] lstDtl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoUpdateReceiving", ReplyAction="http://tempuri.org/IwsINP/DoUpdateReceivingResponse")]
        void DoUpdateReceiving(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpreceiving rec, GENLSYS.MES.DataContracts.tinpreceivingdtl[] lstDtlNew, GENLSYS.MES.DataContracts.tinpreceivingdtl[] lstDtlUpdated, string[] lstDeleted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/DoDeleteReceiving", ReplyAction="http://tempuri.org/IwsINP/DoDeleteReceivingResponse")]
        void DoDeleteReceiving(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetReceivingDetailRecords", ReplyAction="http://tempuri.org/IwsINP/GetReceivingDetailRecordsResponse")]
        System.Data.DataSet GetReceivingDetailRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetReceivingCartonDetailRecords", ReplyAction="http://tempuri.org/IwsINP/GetReceivingCartonDetailRecordsResponse")]
        System.Data.DataSet GetReceivingCartonDetailRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsINP/GetReceivingHeader_Print", ReplyAction="http://tempuri.org/IwsINP/GetReceivingHeader_PrintResponse")]
        System.Data.DataSet GetReceivingHeader_Print(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string recno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsINPChannel : GENLSYS.MES.Win.wsINP.IwsINP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsINPClient : System.ServiceModel.ClientBase<GENLSYS.MES.Win.wsINP.IwsINP>, GENLSYS.MES.Win.wsINP.IwsINP {
        
        public IwsINPClient() {
        }
        
        public IwsINPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsINPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsINPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsINPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetShippingSumRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetShippingSumRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetShippingSumDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetShippingSumDtlRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetUnShippingSumRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetUnShippingSumRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetUnShippingSumDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetUnShippingSumDtlRecords(contextInfo, lstParameters);
        }
        
        public bool HasShipByPlanNo(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingplanno) {
            return base.Channel.HasShipByPlanNo(contextInfo, shippingplanno);
        }
        
        public System.Data.DataSet GetPackingCartonRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo) {
            return base.Channel.GetPackingCartonRecords(contextInfo);
        }
        
        public System.Data.DataSet GetPackingCartonSummaryRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo) {
            return base.Channel.GetPackingCartonSummaryRecords(contextInfo);
        }
        
        public void DoXUnpacking(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string[][] lstunpacking) {
            base.Channel.DoXUnpacking(contextInfo, lstunpacking);
        }
        
        public System.Data.DataSet GetPackingRecDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetPackingRecDtlRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetPackingDtlSumRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetPackingDtlSumRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetPackingDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetPackingDtlRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetHaveNotMovingDtlSumRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetHaveNotMovingDtlSumRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetHaveNotMovingDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetHaveNotMovingDtlRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetHaveNotPackingDtlSumRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetHaveNotPackingDtlSumRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetHaveNotPackingDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetHaveNotPackingDtlRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetLineWarehouseSumRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetLineWarehouseSumRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetLineWarehouseSumDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetLineWarehouseSumDtlRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetPackingRecRetrieveRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetPackingRecRetrieveRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tinpotherpricing[] GetOtherPricingList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetOtherPricingList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetOtherPricingRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetOtherPricingRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tinpotherpricing GetSingleOtherPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleOtherPricing(contextInfo, lstParameters);
        }
        
        public void DoInsertOtherPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpotherpricing otherpricing) {
            base.Channel.DoInsertOtherPricing(contextInfo, otherpricing);
        }
        
        public void DoUpdateOtherPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpotherpricing otherpricing) {
            base.Channel.DoUpdateOtherPricing(contextInfo, otherpricing);
        }
        
        public void DoDeleteOtherPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteOtherPricing(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetValidOtherPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string customerid, System.DateTime dt) {
            return base.Channel.GetValidOtherPricing(contextInfo, customerid, dt);
        }
        
        public void DoInsertRequestPay(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinprequestpay requestPay, GENLSYS.MES.DataContracts.tinprequestpaydtl[] lstDtl) {
            base.Channel.DoInsertRequestPay(contextInfo, requestPay, lstDtl);
        }
        
        public GENLSYS.MES.DataContracts.tinprequestpay GetSingleRequestPay(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleRequestPay(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetRequestPayDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetRequestPayDtlRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tinprepairhis GetSingleRepairHis(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleRepairHis(contextInfo, lstParameters);
        }
        
        public void DoRepaireAdjust(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string repsysid, string reasoncode, int qty) {
            base.Channel.DoRepaireAdjust(contextInfo, repsysid, reasoncode, qty);
        }
        
        public int GetLeftRepairSuccessQty(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string custorderno, string styleno, string color, string size, string step) {
            return base.Channel.GetLeftRepairSuccessQty(contextInfo, custorderno, styleno, color, size, step);
        }
        
        public System.Data.DataSet GetRepairInfoForInspectRpt(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetRepairInfoForInspectRpt(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetRepairFailForInspectRpt(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetRepairFailForInspectRpt(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetShippedForInspectRpt(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetShippedForInspectRpt(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetHeaderInfoForInspectRpt(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetHeaderInfoForInspectRpt(contextInfo, lstParameters);
        }
        
        public void DoReturn(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpreturn inpreturn, GENLSYS.MES.DataContracts.tinpreturndtl[] lstreturndtl) {
            base.Channel.DoReturn(contextInfo, inpreturn, lstreturndtl);
        }
        
        public System.Data.DataSet GetReturnDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetReturnDtlRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tinpreturn GetSingleReturn(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleReturn(contextInfo, lstParameters);
        }
        
        public void DoSupplement(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpsupplement supplement, GENLSYS.MES.DataContracts.tinpsupplementdtl[] lstsupplementdtl) {
            base.Channel.DoSupplement(contextInfo, supplement, lstsupplementdtl);
        }
        
        public System.Data.DataSet GetSupplementDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSupplementDtlRecords(contextInfo, lstParameters);
        }
        
        public void DoSupplementAdjust(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string supldtlsysid, int qty, string isreinspect) {
            base.Channel.DoSupplementAdjust(contextInfo, supldtlsysid, qty, isreinspect);
        }
        
        public GENLSYS.MES.DataContracts.tinpshipping GetSingleShipping(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleShipping(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetShippingRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetShippingRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tinpshippingdtl GetSingleShippingDtl(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleShippingDtl(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetShippingDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetShippingDtlRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetShippingPlanNoRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingsysid) {
            return base.Channel.GetShippingPlanNoRecords(contextInfo, shippingsysid);
        }
        
        public void DoDeleteShipping(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingsysid) {
            base.Channel.DoDeleteShipping(contextInfo, shippingsysid);
        }
        
        public System.Data.DataSet GetShippingDtlForReport(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingsysid) {
            return base.Channel.GetShippingDtlForReport(contextInfo, shippingsysid);
        }
        
        public System.Data.DataSet GetShippingOrigDtlForReport(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingsysid) {
            return base.Channel.GetShippingOrigDtlForReport(contextInfo, shippingsysid);
        }
        
        public System.Data.DataSet GetShippingDtlForWarehouseOut(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingsysid) {
            return base.Channel.GetShippingDtlForWarehouseOut(contextInfo, shippingsysid);
        }
        
        public System.Data.DataSet GetBillForBillingReport(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string shippingsysid) {
            return base.Channel.GetBillForBillingReport(contextInfo, shippingsysid);
        }
        
        public System.Data.DataSet GetShippingDtlCtnRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetShippingDtlCtnRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetShippingPlanRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetShippingPlanRecords(contextInfo, lstParameters);
        }
        
        public void DoShipPlan(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpshippingdtl[] lstshippingdtl, GENLSYS.MES.DataContracts.tinpshippingplan shippingplan) {
            base.Channel.DoShipPlan(contextInfo, lstshippingdtl, shippingplan);
        }
        
        public void DoShipping(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpshipping shipping, GENLSYS.MES.DataContracts.tinpshippingdtlctn[] lstshippingdtlctn, GENLSYS.MES.DataContracts.tinpshippingplan shippingplan, bool isDoShipping) {
            base.Channel.DoShipping(contextInfo, shipping, lstshippingdtlctn, shippingplan, isDoShipping);
        }
        
        public GENLSYS.MES.DataContracts.tinpshippingplan GetSingleShippingPlan(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleShippingPlan(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetReceivingDetail_Print(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string recno) {
            return base.Channel.GetReceivingDetail_Print(contextInfo, recno);
        }
        
        public System.Data.DataSet GetReceivingSumCtnDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetReceivingSumCtnDtlRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetReceivingCtnDtlRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetReceivingCtnDtlRecords(contextInfo, lstParameters);
        }
        
        public void UpdateCartonQty(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string recsysid, string cartonno, string oldstyleno, string oldcolor, string oldsize, int quantity, string color, string size, string styleno) {
            base.Channel.UpdateCartonQty(contextInfo, recsysid, cartonno, oldstyleno, oldcolor, oldsize, quantity, color, size, styleno);
        }
        
        public void DeleteSingleCarton(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string recsysid, string cartonno, string oldstyleno, string oldcolor, string oldsize) {
            base.Channel.DeleteSingleCarton(contextInfo, recsysid, cartonno, oldstyleno, oldcolor, oldsize);
        }
        
        public bool CheckReceivingUsed(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string recsysid) {
            return base.Channel.CheckReceivingUsed(contextInfo, recsysid);
        }
        
        public GENLSYS.MES.DataContracts.tinpiqc[] GetIQCList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetIQCList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetIQCRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetIQCRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tinpiqc GetSingleIQC(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleIQC(contextInfo, lstParameters);
        }
        
        public void DoInsertIQC(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpiqc iqc, GENLSYS.MES.DataContracts.tinpiqcfail[] lstFail, GENLSYS.MES.DataContracts.tinpiqcreturn[] lstReturn) {
            base.Channel.DoInsertIQC(contextInfo, iqc, lstFail, lstReturn);
        }
        
        public void DoUpdateIQC(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpiqc iqc, GENLSYS.MES.DataContracts.tinpiqcfail[] lstFail, GENLSYS.MES.DataContracts.tinpiqcreturn[] lstReturn) {
            base.Channel.DoUpdateIQC(contextInfo, iqc, lstFail, lstReturn);
        }
        
        public void DoDeleteIQC(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteIQC(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetIQCFail(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string iqcsysid) {
            return base.Channel.GetIQCFail(contextInfo, iqcsysid);
        }
        
        public System.Data.DataSet GetIQCReturn(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string iqcsysid, string styleno) {
            return base.Channel.GetIQCReturn(contextInfo, iqcsysid, styleno);
        }
        
        public System.Data.DataSet GetValidIQC(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string customerid) {
            return base.Channel.GetValidIQC(contextInfo, customerid);
        }
        
        public GENLSYS.MES.DataContracts.tinpschedule[] GetScheduleList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetScheduleList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetScheduleRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetScheduleRecords(contextInfo, lstParameters);
        }
        
        public void DoDeleteSchedule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteSchedule(contextInfo, lstParameters);
        }
        
        public void DoInsertSchedule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string yearmonth, GENLSYS.MES.DataContracts.tinpschedule[] lstSchedule) {
            base.Channel.DoInsertSchedule(contextInfo, yearmonth, lstSchedule);
        }
        
        public void DoUpdateSchedule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string yearmonth, GENLSYS.MES.DataContracts.tinpschedule[] lstSchedule) {
            base.Channel.DoUpdateSchedule(contextInfo, yearmonth, lstSchedule);
        }
        
        public System.Data.DataSet GetDailySchedule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string startdate, string enddate) {
            return base.Channel.GetDailySchedule(contextInfo, startdate, enddate);
        }
        
        public System.Data.DataSet GetCustOrderHistoryRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetCustOrderHistoryRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetRepairFailRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetRepairFailRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetRepairStockRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetRepairStockRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tinprepairstock GetSingleRepairStock(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleRepairStock(contextInfo, lstParameters);
        }
        
        public void DoInsertRepair(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinprepairhis repairhis, GENLSYS.MES.DataContracts.tinprepairfail[] lstreasoncode) {
            base.Channel.DoInsertRepair(contextInfo, repairhis, lstreasoncode);
        }
        
        public void DoRepairBack(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinprepairstock repairstock, GENLSYS.MES.DataContracts.tinprepairfail[] lstreasoncode, string jointtype, string signature) {
            base.Channel.DoRepairBack(contextInfo, repairstock, lstreasoncode, jointtype, signature);
        }
        
        public System.Data.DataSet GetRepairHisRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetRepairHisRecords(contextInfo, lstParameters);
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Data.DataSet GetCustOrderRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetCustOrderRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tinpwip[] GetWipList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetWipList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetWipRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetWipRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tinpwip GetSingleWip(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleWip(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetLeftWipRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetLeftWipRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tinpworkorder[] GetWorkOrderList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetWorkOrderList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetWorkOrderRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetWorkOrderRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tinpworkorder GetSingleWorkOrder(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleWorkOrder(contextInfo, lstParameters);
        }
        
        public void DoInsertWorkOrder(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpworkorder workorder, GENLSYS.MES.DataContracts.tinpworkorderdtl[] lstDtl) {
            base.Channel.DoInsertWorkOrder(contextInfo, workorder, lstDtl);
        }
        
        public void DoUpdateWorkOrder(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpworkorder workorder, GENLSYS.MES.DataContracts.tinpworkorderdtl[] lstDtl) {
            base.Channel.DoUpdateWorkOrder(contextInfo, workorder, lstDtl);
        }
        
        public void DoDeleteWorkOrder(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteWorkOrder(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetWorkOrderDetailRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetWorkOrderDetailRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetCustOrderForReceiving(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetCustOrderForReceiving(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tinppricing GetSinglePricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSinglePricing(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetPricingRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetPricingRecords(contextInfo, lstParameters);
        }
        
        public void DoInsertPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinppricing prc, GENLSYS.MES.DataContracts.tinppricingdtl[] lstPrcDtl, GENLSYS.MES.DataContracts.tinppricingdtldef[] lstDef) {
            base.Channel.DoInsertPricing(contextInfo, prc, lstPrcDtl, lstDef);
        }
        
        public void DoUpdatePricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinppricing prc, GENLSYS.MES.DataContracts.tinppricingdtl[] lstPrcDtl, GENLSYS.MES.DataContracts.tinppricingdtldef[] lstDef) {
            base.Channel.DoUpdatePricing(contextInfo, prc, lstPrcDtl, lstDef);
        }
        
        public System.Data.DataSet GetValidPricing(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string customerid, System.DateTime dt) {
            return base.Channel.GetValidPricing(contextInfo, customerid, dt);
        }
        
        public GENLSYS.MES.DataContracts.tinpreceiving[] GetReceivingList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetReceivingList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetReceivingRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetReceivingRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tinpreceiving GetSingleReceiving(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleReceiving(contextInfo, lstParameters);
        }
        
        public void DoInsertReceiving(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpreceiving rec, GENLSYS.MES.DataContracts.tinpreceivingdtl[] lstDtl) {
            base.Channel.DoInsertReceiving(contextInfo, rec, lstDtl);
        }
        
        public void DoUpdateReceiving(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tinpreceiving rec, GENLSYS.MES.DataContracts.tinpreceivingdtl[] lstDtlNew, GENLSYS.MES.DataContracts.tinpreceivingdtl[] lstDtlUpdated, string[] lstDeleted) {
            base.Channel.DoUpdateReceiving(contextInfo, rec, lstDtlNew, lstDtlUpdated, lstDeleted);
        }
        
        public void DoDeleteReceiving(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteReceiving(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetReceivingDetailRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetReceivingDetailRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetReceivingCartonDetailRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetReceivingCartonDetailRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetReceivingHeader_Print(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string recno) {
            return base.Channel.GetReceivingHeader_Print(contextInfo, recno);
        }
    }
}
