//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENLSYS.MES.Win.wsSYS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSYS.IwsSYS")]
    public interface IwsSYS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoDeleteSystemConfig", ReplyAction="http://tempuri.org/IwsSYS/DoDeleteSystemConfigResponse")]
        void DoDeleteSystemConfig(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetAppInfoList", ReplyAction="http://tempuri.org/IwsSYS/GetAppInfoListResponse")]
        GENLSYS.MES.DataContracts.tsysappinfo[] GetAppInfoList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetAppInfoRecords", ReplyAction="http://tempuri.org/IwsSYS/GetAppInfoRecordsResponse")]
        System.Data.DataSet GetAppInfoRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetBillCodeRuleRecords", ReplyAction="http://tempuri.org/IwsSYS/GetBillCodeRuleRecordsResponse")]
        System.Data.DataSet GetBillCodeRuleRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetSingleBillCodeRule", ReplyAction="http://tempuri.org/IwsSYS/GetSingleBillCodeRuleResponse")]
        GENLSYS.MES.DataContracts.tsysbillcoderule GetSingleBillCodeRule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoInsertBillCodeRule", ReplyAction="http://tempuri.org/IwsSYS/DoInsertBillCodeRuleResponse")]
        void DoInsertBillCodeRule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysbillcoderule bcr, GENLSYS.MES.DataContracts.tsysbillcode[] lstBillCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoUpdateBillCodeRule", ReplyAction="http://tempuri.org/IwsSYS/DoUpdateBillCodeRuleResponse")]
        void DoUpdateBillCodeRule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysbillcoderule bcr, GENLSYS.MES.DataContracts.tsysbillcode[] lstBillCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoDeleteBillCodeRule", ReplyAction="http://tempuri.org/IwsSYS/DoDeleteBillCodeRuleResponse")]
        void DoDeleteBillCodeRule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetSingleBillNo", ReplyAction="http://tempuri.org/IwsSYS/GetSingleBillNoResponse")]
        string GetSingleBillNo(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string bcrid, string lockRefId, string baseValue, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstVariablesParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetBatchBillNo", ReplyAction="http://tempuri.org/IwsSYS/GetBatchBillNoResponse")]
        string[] GetBatchBillNo(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string bcrid, int batchNum, string lockRefId, string baseValue, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstVariablesParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetBillCodeList", ReplyAction="http://tempuri.org/IwsSYS/GetBillCodeListResponse")]
        GENLSYS.MES.DataContracts.tsysbillcode[] GetBillCodeList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetBillCodeRecords", ReplyAction="http://tempuri.org/IwsSYS/GetBillCodeRecordsResponse")]
        System.Data.DataSet GetBillCodeRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetSingleBillCode", ReplyAction="http://tempuri.org/IwsSYS/GetSingleBillCodeResponse")]
        GENLSYS.MES.DataContracts.tsysbillcode GetSingleBillCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoInsertBillCode", ReplyAction="http://tempuri.org/IwsSYS/DoInsertBillCodeResponse")]
        void DoInsertBillCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysbillcode billCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoUpdateBillCode", ReplyAction="http://tempuri.org/IwsSYS/DoUpdateBillCodeResponse")]
        void DoUpdateBillCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysbillcode billCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoDeleteBillCode", ReplyAction="http://tempuri.org/IwsSYS/DoDeleteBillCodeResponse")]
        void DoDeleteBillCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/UnlockBill", ReplyAction="http://tempuri.org/IwsSYS/UnlockBillResponse")]
        void UnlockBill(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string bcrid, string lockRefId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/ResetBill", ReplyAction="http://tempuri.org/IwsSYS/ResetBillResponse")]
        void ResetBill(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string bcrid, string lockRefId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetSessionRecords", ReplyAction="http://tempuri.org/IwsSYS/GetSessionRecordsResponse")]
        System.Data.DataSet GetSessionRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetSingleSession", ReplyAction="http://tempuri.org/IwsSYS/GetSingleSessionResponse")]
        GENLSYS.MES.DataContracts.tsyssession GetSingleSession(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoUpdateSession", ReplyAction="http://tempuri.org/IwsSYS/DoUpdateSessionResponse")]
        void DoUpdateSession(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsyssession session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoUpdateLock", ReplyAction="http://tempuri.org/IwsSYS/DoUpdateLockResponse")]
        void DoUpdateLock(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string[] lstSessionId, string flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoUpdateKill", ReplyAction="http://tempuri.org/IwsSYS/DoUpdateKillResponse")]
        void DoUpdateKill(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string[] lstSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetSessionHisRecords", ReplyAction="http://tempuri.org/IwsSYS/GetSessionHisRecordsResponse")]
        System.Data.DataSet GetSessionHisRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string userid, string machine, string ipaddress, string shift, System.DateTime fromlogontime, System.DateTime tologontime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoSessionMultiDelete", ReplyAction="http://tempuri.org/IwsSYS/DoSessionMultiDeleteResponse")]
        void DoSessionMultiDelete(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string[] lstSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetAllSystemConfigValue", ReplyAction="http://tempuri.org/IwsSYS/GetAllSystemConfigValueResponse")]
        GENLSYS.MES.DataContracts.tsyssystemconfig[] GetAllSystemConfigValue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetSystemConfigList", ReplyAction="http://tempuri.org/IwsSYS/GetSystemConfigListResponse")]
        GENLSYS.MES.DataContracts.tsyssystemconfig[] GetSystemConfigList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetSystemConfigRecords", ReplyAction="http://tempuri.org/IwsSYS/GetSystemConfigRecordsResponse")]
        System.Data.DataSet GetSystemConfigRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetSingleSystemConfig", ReplyAction="http://tempuri.org/IwsSYS/GetSingleSystemConfigResponse")]
        GENLSYS.MES.DataContracts.tsyssystemconfig GetSingleSystemConfig(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoInsertSystemConfig", ReplyAction="http://tempuri.org/IwsSYS/DoInsertSystemConfigResponse")]
        void DoInsertSystemConfig(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsyssystemconfig systemConfig);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoUpdateSystemConfig", ReplyAction="http://tempuri.org/IwsSYS/DoUpdateSystemConfigResponse")]
        void DoUpdateSystemConfig(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsyssystemconfig systemConfig);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetServerDateTime", ReplyAction="http://tempuri.org/IwsSYS/GetServerDateTimeResponse")]
        string GetServerDateTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetServerIPAddress", ReplyAction="http://tempuri.org/IwsSYS/GetServerIPAddressResponse")]
        string[] GetServerIPAddress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetAttributeList", ReplyAction="http://tempuri.org/IwsSYS/GetAttributeListResponse")]
        GENLSYS.MES.DataContracts.tsysattributevalue[] GetAttributeList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetAttributeRecords", ReplyAction="http://tempuri.org/IwsSYS/GetAttributeRecordsResponse")]
        System.Data.DataSet GetAttributeRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetSingleAttribute", ReplyAction="http://tempuri.org/IwsSYS/GetSingleAttributeResponse")]
        GENLSYS.MES.DataContracts.tsysattributevalue GetSingleAttribute(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DeleteMultiAttribute", ReplyAction="http://tempuri.org/IwsSYS/DeleteMultiAttributeResponse")]
        void DeleteMultiAttribute(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DeleteSingleAttribute", ReplyAction="http://tempuri.org/IwsSYS/DeleteSingleAttributeResponse")]
        void DeleteSingleAttribute(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysattributevalue obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/InsertMultiAttribute", ReplyAction="http://tempuri.org/IwsSYS/InsertMultiAttributeResponse")]
        void InsertMultiAttribute(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysattributevalue[] lstAttributes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/InsertSingleAttribute", ReplyAction="http://tempuri.org/IwsSYS/InsertSingleAttributeResponse")]
        void InsertSingleAttribute(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysattributevalue objAttribute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetAttributeTemplateList", ReplyAction="http://tempuri.org/IwsSYS/GetAttributeTemplateListResponse")]
        GENLSYS.MES.DataContracts.tsysattrtplate[] GetAttributeTemplateList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetAttributeTemplateRecords", ReplyAction="http://tempuri.org/IwsSYS/GetAttributeTemplateRecordsResponse")]
        System.Data.DataSet GetAttributeTemplateRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetSingleAttributeTemplate", ReplyAction="http://tempuri.org/IwsSYS/GetSingleAttributeTemplateResponse")]
        GENLSYS.MES.DataContracts.tsysattrtplate GetSingleAttributeTemplate(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetMaxAttributeId", ReplyAction="http://tempuri.org/IwsSYS/GetMaxAttributeIdResponse")]
        decimal GetMaxAttributeId(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/InsertAttributeTemplate", ReplyAction="http://tempuri.org/IwsSYS/InsertAttributeTemplateResponse")]
        void InsertAttributeTemplate(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysattrtplate template, GENLSYS.MES.DataContracts.tsysattrtplatedtl[] lstAttribute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/UpdateAttributeTemplate", ReplyAction="http://tempuri.org/IwsSYS/UpdateAttributeTemplateResponse")]
        void UpdateAttributeTemplate(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysattrtplate template, GENLSYS.MES.DataContracts.tsysattrtplatedtl[] lstAttribute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DeleteAttributeTemplate", ReplyAction="http://tempuri.org/IwsSYS/DeleteAttributeTemplateResponse")]
        void DeleteAttributeTemplate(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetMaxSeqno", ReplyAction="http://tempuri.org/IwsSYS/GetMaxSeqnoResponse")]
        decimal GetMaxSeqno(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string usedby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetAttributeTemplateDetailList", ReplyAction="http://tempuri.org/IwsSYS/GetAttributeTemplateDetailListResponse")]
        GENLSYS.MES.DataContracts.tsysattrtplatedtl[] GetAttributeTemplateDetailList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetAttributeTemplateDetailRecords", ReplyAction="http://tempuri.org/IwsSYS/GetAttributeTemplateDetailRecordsResponse")]
        System.Data.DataSet GetAttributeTemplateDetailRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetStaticValueList", ReplyAction="http://tempuri.org/IwsSYS/GetStaticValueListResponse")]
        GENLSYS.MES.DataContracts.tsysstaticvalue[] GetStaticValueList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetStaticValueRecords", ReplyAction="http://tempuri.org/IwsSYS/GetStaticValueRecordsResponse")]
        System.Data.DataSet GetStaticValueRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetSingleStaticValue", ReplyAction="http://tempuri.org/IwsSYS/GetSingleStaticValueResponse")]
        GENLSYS.MES.DataContracts.tsysstaticvalue GetSingleStaticValue(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoInsertStaticValue", ReplyAction="http://tempuri.org/IwsSYS/DoInsertStaticValueResponse")]
        void DoInsertStaticValue(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysstaticvalue staticValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoUpdateStaticValue", ReplyAction="http://tempuri.org/IwsSYS/DoUpdateStaticValueResponse")]
        void DoUpdateStaticValue(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysstaticvalue staticValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/DoDeleteStaticValue", ReplyAction="http://tempuri.org/IwsSYS/DoDeleteStaticValueResponse")]
        void DoDeleteStaticValue(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetMenuConfigList", ReplyAction="http://tempuri.org/IwsSYS/GetMenuConfigListResponse")]
        GENLSYS.MES.DataContracts.tsysmenuconfig[] GetMenuConfigList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetTopMenuList", ReplyAction="http://tempuri.org/IwsSYS/GetTopMenuListResponse")]
        GENLSYS.MES.DataContracts.tsysmenuconfig[] GetTopMenuList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string menutype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSYS/GetBillCodeRuleList", ReplyAction="http://tempuri.org/IwsSYS/GetBillCodeRuleListResponse")]
        GENLSYS.MES.DataContracts.tsysbillcoderule[] GetBillCodeRuleList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsSYSChannel : GENLSYS.MES.Win.wsSYS.IwsSYS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsSYSClient : System.ServiceModel.ClientBase<GENLSYS.MES.Win.wsSYS.IwsSYS>, GENLSYS.MES.Win.wsSYS.IwsSYS {
        
        public IwsSYSClient() {
        }
        
        public IwsSYSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsSYSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsSYSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsSYSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoDeleteSystemConfig(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteSystemConfig(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tsysappinfo[] GetAppInfoList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetAppInfoList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetAppInfoRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetAppInfoRecords(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetBillCodeRuleRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetBillCodeRuleRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tsysbillcoderule GetSingleBillCodeRule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleBillCodeRule(contextInfo, lstParameters);
        }
        
        public void DoInsertBillCodeRule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysbillcoderule bcr, GENLSYS.MES.DataContracts.tsysbillcode[] lstBillCode) {
            base.Channel.DoInsertBillCodeRule(contextInfo, bcr, lstBillCode);
        }
        
        public void DoUpdateBillCodeRule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysbillcoderule bcr, GENLSYS.MES.DataContracts.tsysbillcode[] lstBillCode) {
            base.Channel.DoUpdateBillCodeRule(contextInfo, bcr, lstBillCode);
        }
        
        public void DoDeleteBillCodeRule(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteBillCodeRule(contextInfo, lstParameters);
        }
        
        public string GetSingleBillNo(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string bcrid, string lockRefId, string baseValue, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstVariablesParameters) {
            return base.Channel.GetSingleBillNo(contextInfo, bcrid, lockRefId, baseValue, lstVariablesParameters);
        }
        
        public string[] GetBatchBillNo(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string bcrid, int batchNum, string lockRefId, string baseValue, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstVariablesParameters) {
            return base.Channel.GetBatchBillNo(contextInfo, bcrid, batchNum, lockRefId, baseValue, lstVariablesParameters);
        }
        
        public GENLSYS.MES.DataContracts.tsysbillcode[] GetBillCodeList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetBillCodeList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetBillCodeRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetBillCodeRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tsysbillcode GetSingleBillCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleBillCode(contextInfo, lstParameters);
        }
        
        public void DoInsertBillCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysbillcode billCode) {
            base.Channel.DoInsertBillCode(contextInfo, billCode);
        }
        
        public void DoUpdateBillCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysbillcode billCode) {
            base.Channel.DoUpdateBillCode(contextInfo, billCode);
        }
        
        public void DoDeleteBillCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteBillCode(contextInfo, lstParameters);
        }
        
        public void UnlockBill(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string bcrid, string lockRefId) {
            base.Channel.UnlockBill(contextInfo, bcrid, lockRefId);
        }
        
        public void ResetBill(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string bcrid, string lockRefId) {
            base.Channel.ResetBill(contextInfo, bcrid, lockRefId);
        }
        
        public System.Data.DataSet GetSessionRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSessionRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tsyssession GetSingleSession(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleSession(contextInfo, lstParameters);
        }
        
        public void DoUpdateSession(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsyssession session) {
            base.Channel.DoUpdateSession(contextInfo, session);
        }
        
        public void DoUpdateLock(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string[] lstSessionId, string flag) {
            base.Channel.DoUpdateLock(contextInfo, lstSessionId, flag);
        }
        
        public void DoUpdateKill(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string[] lstSessionId) {
            base.Channel.DoUpdateKill(contextInfo, lstSessionId);
        }
        
        public System.Data.DataSet GetSessionHisRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string userid, string machine, string ipaddress, string shift, System.DateTime fromlogontime, System.DateTime tologontime) {
            return base.Channel.GetSessionHisRecords(contextInfo, userid, machine, ipaddress, shift, fromlogontime, tologontime);
        }
        
        public void DoSessionMultiDelete(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string[] lstSessionId) {
            base.Channel.DoSessionMultiDelete(contextInfo, lstSessionId);
        }
        
        public GENLSYS.MES.DataContracts.tsyssystemconfig[] GetAllSystemConfigValue() {
            return base.Channel.GetAllSystemConfigValue();
        }
        
        public GENLSYS.MES.DataContracts.tsyssystemconfig[] GetSystemConfigList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSystemConfigList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetSystemConfigRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSystemConfigRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tsyssystemconfig GetSingleSystemConfig(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleSystemConfig(contextInfo, lstParameters);
        }
        
        public void DoInsertSystemConfig(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsyssystemconfig systemConfig) {
            base.Channel.DoInsertSystemConfig(contextInfo, systemConfig);
        }
        
        public void DoUpdateSystemConfig(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsyssystemconfig systemConfig) {
            base.Channel.DoUpdateSystemConfig(contextInfo, systemConfig);
        }
        
        public string GetServerDateTime() {
            return base.Channel.GetServerDateTime();
        }
        
        public string[] GetServerIPAddress() {
            return base.Channel.GetServerIPAddress();
        }
        
        public GENLSYS.MES.DataContracts.tsysattributevalue[] GetAttributeList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetAttributeList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetAttributeRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetAttributeRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tsysattributevalue GetSingleAttribute(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleAttribute(contextInfo, lstParameters);
        }
        
        public void DeleteMultiAttribute(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DeleteMultiAttribute(contextInfo, lstParameters);
        }
        
        public void DeleteSingleAttribute(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysattributevalue obj) {
            base.Channel.DeleteSingleAttribute(contextInfo, obj);
        }
        
        public void InsertMultiAttribute(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysattributevalue[] lstAttributes) {
            base.Channel.InsertMultiAttribute(contextInfo, lstAttributes);
        }
        
        public void InsertSingleAttribute(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysattributevalue objAttribute) {
            base.Channel.InsertSingleAttribute(contextInfo, objAttribute);
        }
        
        public GENLSYS.MES.DataContracts.tsysattrtplate[] GetAttributeTemplateList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetAttributeTemplateList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetAttributeTemplateRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetAttributeTemplateRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tsysattrtplate GetSingleAttributeTemplate(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleAttributeTemplate(contextInfo, lstParameters);
        }
        
        public decimal GetMaxAttributeId(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo) {
            return base.Channel.GetMaxAttributeId(contextInfo);
        }
        
        public void InsertAttributeTemplate(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysattrtplate template, GENLSYS.MES.DataContracts.tsysattrtplatedtl[] lstAttribute) {
            base.Channel.InsertAttributeTemplate(contextInfo, template, lstAttribute);
        }
        
        public void UpdateAttributeTemplate(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysattrtplate template, GENLSYS.MES.DataContracts.tsysattrtplatedtl[] lstAttribute) {
            base.Channel.UpdateAttributeTemplate(contextInfo, template, lstAttribute);
        }
        
        public void DeleteAttributeTemplate(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DeleteAttributeTemplate(contextInfo, lstParameters);
        }
        
        public decimal GetMaxSeqno(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string usedby) {
            return base.Channel.GetMaxSeqno(contextInfo, usedby);
        }
        
        public GENLSYS.MES.DataContracts.tsysattrtplatedtl[] GetAttributeTemplateDetailList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetAttributeTemplateDetailList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetAttributeTemplateDetailRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetAttributeTemplateDetailRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tsysstaticvalue[] GetStaticValueList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetStaticValueList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetStaticValueRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetStaticValueRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tsysstaticvalue GetSingleStaticValue(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleStaticValue(contextInfo, lstParameters);
        }
        
        public void DoInsertStaticValue(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysstaticvalue staticValue) {
            base.Channel.DoInsertStaticValue(contextInfo, staticValue);
        }
        
        public void DoUpdateStaticValue(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tsysstaticvalue staticValue) {
            base.Channel.DoUpdateStaticValue(contextInfo, staticValue);
        }
        
        public void DoDeleteStaticValue(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteStaticValue(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tsysmenuconfig[] GetMenuConfigList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetMenuConfigList(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tsysmenuconfig[] GetTopMenuList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string menutype) {
            return base.Channel.GetTopMenuList(contextInfo, menutype);
        }
        
        public GENLSYS.MES.DataContracts.tsysbillcoderule[] GetBillCodeRuleList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetBillCodeRuleList(contextInfo, lstParameters);
        }
    }
}
