//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENLSYS.MES.Win.wsMDL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsMDL.IwsMDL")]
    public interface IwsMDL {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetSingleReasonCode", ReplyAction="http://tempuri.org/IwsMDL/GetSingleReasonCodeResponse")]
        GENLSYS.MES.DataContracts.tmdlreasoncode GetSingleReasonCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoInsertReasonCode", ReplyAction="http://tempuri.org/IwsMDL/DoInsertReasonCodeResponse")]
        void DoInsertReasonCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlreasoncode reasoncode, GENLSYS.MES.DataContracts.tmdlreasoncodestep[] lstReasonCodeStep, GENLSYS.MES.DataContracts.tsysattributevalue[] lstAttribute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoUpdateReasonCode", ReplyAction="http://tempuri.org/IwsMDL/DoUpdateReasonCodeResponse")]
        void DoUpdateReasonCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlreasoncode reasoncode, GENLSYS.MES.DataContracts.tmdlreasoncodestep[] lstReasonCodeStep, GENLSYS.MES.DataContracts.tsysattributevalue[] lstAttribute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoDeleteReasonCode", ReplyAction="http://tempuri.org/IwsMDL/DoDeleteReasonCodeResponse")]
        void DoDeleteReasonCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetReasonCodeStep", ReplyAction="http://tempuri.org/IwsMDL/GetReasonCodeStepResponse")]
        System.Data.DataSet GetReasonCodeStep(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string reasoncode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetShiftRecords", ReplyAction="http://tempuri.org/IwsMDL/GetShiftRecordsResponse")]
        System.Data.DataSet GetShiftRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetShiftList", ReplyAction="http://tempuri.org/IwsMDL/GetShiftListResponse")]
        GENLSYS.MES.DataContracts.tmdlshift[] GetShiftList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetSingleShift", ReplyAction="http://tempuri.org/IwsMDL/GetSingleShiftResponse")]
        GENLSYS.MES.DataContracts.tmdlshift GetSingleShift(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoInsertShift", ReplyAction="http://tempuri.org/IwsMDL/DoInsertShiftResponse")]
        void DoInsertShift(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlshift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoUpdateShift", ReplyAction="http://tempuri.org/IwsMDL/DoUpdateShiftResponse")]
        void DoUpdateShift(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlshift shift);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoDeleteShift", ReplyAction="http://tempuri.org/IwsMDL/DoDeleteShiftResponse")]
        void DoDeleteShift(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetWorkGroupList", ReplyAction="http://tempuri.org/IwsMDL/GetWorkGroupListResponse")]
        GENLSYS.MES.DataContracts.tmdlworkgroup[] GetWorkGroupList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetWorkGroupRecords", ReplyAction="http://tempuri.org/IwsMDL/GetWorkGroupRecordsResponse")]
        System.Data.DataSet GetWorkGroupRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetSingleWorkGroup", ReplyAction="http://tempuri.org/IwsMDL/GetSingleWorkGroupResponse")]
        GENLSYS.MES.DataContracts.tmdlworkgroup GetSingleWorkGroup(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoInsertWorkGroup", ReplyAction="http://tempuri.org/IwsMDL/DoInsertWorkGroupResponse")]
        void DoInsertWorkGroup(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlworkgroup location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoUpdateWorkGroup", ReplyAction="http://tempuri.org/IwsMDL/DoUpdateWorkGroupResponse")]
        void DoUpdateWorkGroup(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlworkgroup location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoDeleteWorkGroup", ReplyAction="http://tempuri.org/IwsMDL/DoDeleteWorkGroupResponse")]
        void DoDeleteWorkGroup(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetExchangeList", ReplyAction="http://tempuri.org/IwsMDL/GetExchangeListResponse")]
        GENLSYS.MES.DataContracts.tmdlexchange[] GetExchangeList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetExchangeRecords", ReplyAction="http://tempuri.org/IwsMDL/GetExchangeRecordsResponse")]
        System.Data.DataSet GetExchangeRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetSingleExchange", ReplyAction="http://tempuri.org/IwsMDL/GetSingleExchangeResponse")]
        GENLSYS.MES.DataContracts.tmdlexchange GetSingleExchange(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoInsertExchange", ReplyAction="http://tempuri.org/IwsMDL/DoInsertExchangeResponse")]
        void DoInsertExchange(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlexchange exchange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoUpdateExchange", ReplyAction="http://tempuri.org/IwsMDL/DoUpdateExchangeResponse")]
        void DoUpdateExchange(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlexchange exchange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoDeleteExchange", ReplyAction="http://tempuri.org/IwsMDL/DoDeleteExchangeResponse")]
        void DoDeleteExchange(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetValidExchange", ReplyAction="http://tempuri.org/IwsMDL/GetValidExchangeResponse")]
        System.Data.DataSet GetValidExchange(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetEmployeeList", ReplyAction="http://tempuri.org/IwsMDL/GetEmployeeListResponse")]
        GENLSYS.MES.DataContracts.tmdlemployee[] GetEmployeeList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetEmployeeRecords", ReplyAction="http://tempuri.org/IwsMDL/GetEmployeeRecordsResponse")]
        System.Data.DataSet GetEmployeeRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetSingleEmployee", ReplyAction="http://tempuri.org/IwsMDL/GetSingleEmployeeResponse")]
        GENLSYS.MES.DataContracts.tmdlemployee GetSingleEmployee(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoInsertEmployee", ReplyAction="http://tempuri.org/IwsMDL/DoInsertEmployeeResponse")]
        void DoInsertEmployee(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlemployee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoUpdateEmployee", ReplyAction="http://tempuri.org/IwsMDL/DoUpdateEmployeeResponse")]
        void DoUpdateEmployee(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlemployee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoDeleteEmployee", ReplyAction="http://tempuri.org/IwsMDL/DoDeleteEmployeeResponse")]
        void DoDeleteEmployee(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetEmployeeTypeList", ReplyAction="http://tempuri.org/IwsMDL/GetEmployeeTypeListResponse")]
        GENLSYS.MES.DataContracts.tmdlemployeetype[] GetEmployeeTypeList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetEmployeeTypeRecords", ReplyAction="http://tempuri.org/IwsMDL/GetEmployeeTypeRecordsResponse")]
        System.Data.DataSet GetEmployeeTypeRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetSingleEmployeeType", ReplyAction="http://tempuri.org/IwsMDL/GetSingleEmployeeTypeResponse")]
        GENLSYS.MES.DataContracts.tmdlemployeetype GetSingleEmployeeType(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoInsertEmployeeType", ReplyAction="http://tempuri.org/IwsMDL/DoInsertEmployeeTypeResponse")]
        void DoInsertEmployeeType(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlemployeetype employeetype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoUpdateEmployeeType", ReplyAction="http://tempuri.org/IwsMDL/DoUpdateEmployeeTypeResponse")]
        void DoUpdateEmployeeType(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlemployeetype employeetype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoDeleteEmployeeType", ReplyAction="http://tempuri.org/IwsMDL/DoDeleteEmployeeTypeResponse")]
        void DoDeleteEmployeeType(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetCustomerList", ReplyAction="http://tempuri.org/IwsMDL/GetCustomerListResponse")]
        GENLSYS.MES.DataContracts.tmdlcustomer[] GetCustomerList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetCustomerRecords", ReplyAction="http://tempuri.org/IwsMDL/GetCustomerRecordsResponse")]
        System.Data.DataSet GetCustomerRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetSingleCustomer", ReplyAction="http://tempuri.org/IwsMDL/GetSingleCustomerResponse")]
        GENLSYS.MES.DataContracts.tmdlcustomer GetSingleCustomer(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoInsertCustomer", ReplyAction="http://tempuri.org/IwsMDL/DoInsertCustomerResponse")]
        void DoInsertCustomer(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlcustomer customer, GENLSYS.MES.DataContracts.tmdlcontact[] lstContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoUpdateCustomer", ReplyAction="http://tempuri.org/IwsMDL/DoUpdateCustomerResponse")]
        void DoUpdateCustomer(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlcustomer customer, GENLSYS.MES.DataContracts.tmdlcontact[] lstContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoDeleteCustomer", ReplyAction="http://tempuri.org/IwsMDL/DoDeleteCustomerResponse")]
        void DoDeleteCustomer(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetContactRecords", ReplyAction="http://tempuri.org/IwsMDL/GetContactRecordsResponse")]
        System.Data.DataSet GetContactRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetReasonCategoryList", ReplyAction="http://tempuri.org/IwsMDL/GetReasonCategoryListResponse")]
        GENLSYS.MES.DataContracts.tmdlreasoncategory[] GetReasonCategoryList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetReasonCategoryRecords", ReplyAction="http://tempuri.org/IwsMDL/GetReasonCategoryRecordsResponse")]
        System.Data.DataSet GetReasonCategoryRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetSingleReasonCategory", ReplyAction="http://tempuri.org/IwsMDL/GetSingleReasonCategoryResponse")]
        GENLSYS.MES.DataContracts.tmdlreasoncategory GetSingleReasonCategory(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoInsertReasonCategory", ReplyAction="http://tempuri.org/IwsMDL/DoInsertReasonCategoryResponse")]
        void DoInsertReasonCategory(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlreasoncategory reasoncategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoUpdateReasonCategory", ReplyAction="http://tempuri.org/IwsMDL/DoUpdateReasonCategoryResponse")]
        void DoUpdateReasonCategory(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlreasoncategory reasoncategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/DoDeleteReasonCategory", ReplyAction="http://tempuri.org/IwsMDL/DoDeleteReasonCategoryResponse")]
        void DoDeleteReasonCategory(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetReasonCodeList_ByCategoryStep", ReplyAction="http://tempuri.org/IwsMDL/GetReasonCodeList_ByCategoryStepResponse")]
        GENLSYS.MES.DataContracts.tmdlreasoncode[] GetReasonCodeList_ByCategoryStep(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string reasonCodeCategory, string stepsysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetReasonCodeList", ReplyAction="http://tempuri.org/IwsMDL/GetReasonCodeListResponse")]
        GENLSYS.MES.DataContracts.tmdlreasoncode[] GetReasonCodeList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsMDL/GetReasonCodeRecords", ReplyAction="http://tempuri.org/IwsMDL/GetReasonCodeRecordsResponse")]
        System.Data.DataSet GetReasonCodeRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsMDLChannel : GENLSYS.MES.Win.wsMDL.IwsMDL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsMDLClient : System.ServiceModel.ClientBase<GENLSYS.MES.Win.wsMDL.IwsMDL>, GENLSYS.MES.Win.wsMDL.IwsMDL {
        
        public IwsMDLClient() {
        }
        
        public IwsMDLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsMDLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsMDLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsMDLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GENLSYS.MES.DataContracts.tmdlreasoncode GetSingleReasonCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleReasonCode(contextInfo, lstParameters);
        }
        
        public void DoInsertReasonCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlreasoncode reasoncode, GENLSYS.MES.DataContracts.tmdlreasoncodestep[] lstReasonCodeStep, GENLSYS.MES.DataContracts.tsysattributevalue[] lstAttribute) {
            base.Channel.DoInsertReasonCode(contextInfo, reasoncode, lstReasonCodeStep, lstAttribute);
        }
        
        public void DoUpdateReasonCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlreasoncode reasoncode, GENLSYS.MES.DataContracts.tmdlreasoncodestep[] lstReasonCodeStep, GENLSYS.MES.DataContracts.tsysattributevalue[] lstAttribute) {
            base.Channel.DoUpdateReasonCode(contextInfo, reasoncode, lstReasonCodeStep, lstAttribute);
        }
        
        public void DoDeleteReasonCode(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteReasonCode(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetReasonCodeStep(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string reasoncode) {
            return base.Channel.GetReasonCodeStep(contextInfo, reasoncode);
        }
        
        public System.Data.DataSet GetShiftRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetShiftRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlshift[] GetShiftList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetShiftList(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlshift GetSingleShift(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleShift(contextInfo, lstParameters);
        }
        
        public void DoInsertShift(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlshift shift) {
            base.Channel.DoInsertShift(contextInfo, shift);
        }
        
        public void DoUpdateShift(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlshift shift) {
            base.Channel.DoUpdateShift(contextInfo, shift);
        }
        
        public void DoDeleteShift(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteShift(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlworkgroup[] GetWorkGroupList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetWorkGroupList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetWorkGroupRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetWorkGroupRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlworkgroup GetSingleWorkGroup(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleWorkGroup(contextInfo, lstParameters);
        }
        
        public void DoInsertWorkGroup(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlworkgroup location) {
            base.Channel.DoInsertWorkGroup(contextInfo, location);
        }
        
        public void DoUpdateWorkGroup(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlworkgroup location) {
            base.Channel.DoUpdateWorkGroup(contextInfo, location);
        }
        
        public void DoDeleteWorkGroup(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteWorkGroup(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlexchange[] GetExchangeList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetExchangeList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetExchangeRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetExchangeRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlexchange GetSingleExchange(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleExchange(contextInfo, lstParameters);
        }
        
        public void DoInsertExchange(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlexchange exchange) {
            base.Channel.DoInsertExchange(contextInfo, exchange);
        }
        
        public void DoUpdateExchange(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlexchange exchange) {
            base.Channel.DoUpdateExchange(contextInfo, exchange);
        }
        
        public void DoDeleteExchange(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteExchange(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetValidExchange(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, System.DateTime dt) {
            return base.Channel.GetValidExchange(contextInfo, dt);
        }
        
        public GENLSYS.MES.DataContracts.tmdlemployee[] GetEmployeeList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetEmployeeList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetEmployeeRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetEmployeeRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlemployee GetSingleEmployee(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleEmployee(contextInfo, lstParameters);
        }
        
        public void DoInsertEmployee(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlemployee employee) {
            base.Channel.DoInsertEmployee(contextInfo, employee);
        }
        
        public void DoUpdateEmployee(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlemployee employee) {
            base.Channel.DoUpdateEmployee(contextInfo, employee);
        }
        
        public void DoDeleteEmployee(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteEmployee(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlemployeetype[] GetEmployeeTypeList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetEmployeeTypeList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetEmployeeTypeRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetEmployeeTypeRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlemployeetype GetSingleEmployeeType(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleEmployeeType(contextInfo, lstParameters);
        }
        
        public void DoInsertEmployeeType(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlemployeetype employeetype) {
            base.Channel.DoInsertEmployeeType(contextInfo, employeetype);
        }
        
        public void DoUpdateEmployeeType(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlemployeetype employeetype) {
            base.Channel.DoUpdateEmployeeType(contextInfo, employeetype);
        }
        
        public void DoDeleteEmployeeType(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteEmployeeType(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlcustomer[] GetCustomerList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetCustomerList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetCustomerRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetCustomerRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlcustomer GetSingleCustomer(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleCustomer(contextInfo, lstParameters);
        }
        
        public void DoInsertCustomer(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlcustomer customer, GENLSYS.MES.DataContracts.tmdlcontact[] lstContact) {
            base.Channel.DoInsertCustomer(contextInfo, customer, lstContact);
        }
        
        public void DoUpdateCustomer(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlcustomer customer, GENLSYS.MES.DataContracts.tmdlcontact[] lstContact) {
            base.Channel.DoUpdateCustomer(contextInfo, customer, lstContact);
        }
        
        public void DoDeleteCustomer(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteCustomer(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetContactRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetContactRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlreasoncategory[] GetReasonCategoryList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetReasonCategoryList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetReasonCategoryRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetReasonCategoryRecords(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlreasoncategory GetSingleReasonCategory(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetSingleReasonCategory(contextInfo, lstParameters);
        }
        
        public void DoInsertReasonCategory(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlreasoncategory reasoncategory) {
            base.Channel.DoInsertReasonCategory(contextInfo, reasoncategory);
        }
        
        public void DoUpdateReasonCategory(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.tmdlreasoncategory reasoncategory) {
            base.Channel.DoUpdateReasonCategory(contextInfo, reasoncategory);
        }
        
        public void DoDeleteReasonCategory(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            base.Channel.DoDeleteReasonCategory(contextInfo, lstParameters);
        }
        
        public GENLSYS.MES.DataContracts.tmdlreasoncode[] GetReasonCodeList_ByCategoryStep(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, string reasonCodeCategory, string stepsysid) {
            return base.Channel.GetReasonCodeList_ByCategoryStep(contextInfo, reasonCodeCategory, stepsysid);
        }
        
        public GENLSYS.MES.DataContracts.tmdlreasoncode[] GetReasonCodeList(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetReasonCodeList(contextInfo, lstParameters);
        }
        
        public System.Data.DataSet GetReasonCodeRecords(GENLSYS.MES.DataContracts.Common.ContextInfo contextInfo, GENLSYS.MES.DataContracts.Common.MESParameterInfo[] lstParameters) {
            return base.Channel.GetReasonCodeRecords(contextInfo, lstParameters);
        }
    }
}
